server:
  port: 18091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart
    username: root
    password: ROOT
  redis:
    host: 212.64.52.80
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 80
        max-size: 200
        keep-alive: 90s
        queue-capacity: 10000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 90
  rabbitmq:
    host: 192.168.8.95
    virtual-host: /dpc
    username: dpc
    password: dpc
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
feign:
  sentinel:
    enabled: true

auth:
  jwt:
    pubKeyPath: D:\dpc\rsa\\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.cart.entity
#    unick: unick