server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_ums
    username: root
    password: ROOT
  redis:
    host: 212.64.52.80
    port: 6379
#  rabbitmq:
#    host: 212.64.52.80
#    virtual-host: /dpc
#    username: dpc
#    password: dpc
#    publisher-returns: true
#    publisher-confirm-type: simple
#    listener:
#      simple:
#        prefetch: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto
#logging:
#  level:
#    com.atguigu.gmall: debug